### ISSUE TITLE
Review static analysis results for couchbase-lite-java-core

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1003]
Total: 3991 items

##### Abstraction Issues (1400 items) - NOT NOW
- We might not work for this immediately. When we will work for Simple API we need to review Interface and Implmementation.

##### Assignment Issues (95 items)  - Partially Fix
- Assignmnet to static field from instance context (1 item) (ex ReplicationInternal) <- thread safty consern for this implmentation  - FIX
- Others are not necessary to fix immediately.

##### Class metrics (60 items) - FIX
- It is nice to fix the suggestion by static analysis tool. By fix suggestions, our codes become more maintainable.

##### Class structure (7 items) - FIX
- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Cloning issues (1 item) - FIX
- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Code maturity issues (13 items) - FIX
- Call to 'printStackTrace()' - Stacktrace missleads developers should fix this now.
- Deprecated API usage (4 items) - Needs to fix now.
- Uses of System.err or System.out - Needs to fix now

##### Code style issues (15 items) - FIX
- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Compiler issues (74 items) - FIX
- most of warning comes from ObjectMapper.readValue(). Should solve Map to Map<String, Object> casting

##### Control flow issues (22 items)
- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Data flow issus (44 items) - Fix
- Boolean method is alwasy invrted <--??
- Redundant local variable <- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 
- Sceope of variable is too broad <- As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Declaration redundancy (785 items) - Fix
- Might not be necessary to fix all of suggestions. In general, this is low hangging fruites. It is better to address now.

##### Encapsulation issues (49 items)
-  As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### Error handling (22 items) - Fix
-  As this does not cause the problem, but this is low hangging fruits. It is better to address now. 

##### General (6 items) - Not Fix
- Not fix now.

##### Imports (5 items) - Fix
- [x] 1020 - delete unused import 

##### Java language level migration aids (24 items) - Fix
- Might improve performance slightly - Fix

##### Javadoc Issues (96 items) - Not Fix
- Not work this time

##### Memory Issues (23 items) - Partially fix
- Anonymous class may be a named 'static' inner class - Not fix now
- Return of instance of anonymous class - Not Fix now
- Zero-length array allocation (2 items) - Fix now.

##### Method metrics (49 items)  - Not Fix
- Not now

##### Performance issues (239 items) - Fix
- Most of suggestions are not complicated to fix. Fix now.
- [x] #1018 - Part 1
- [x] #1022 - apply static method if applicable

##### Probable bugs (104 items) - Review & Fix
- Needs to review one by one.

##### Resource management issues (7 items) - Fix **IMPORTANT**
- [x] #1016 Must Fix!!!
- Base64.java is third party code. suppress warnings
- `SymmetricKey.decryptStream()` apply no-inspection

##### Security issues (709 issues) - Not fix
- most of suggestions is method extension: I am not sure if this required
- other suggestions are related with serialization: Also I am not sure about this now.

##### Threading issues (128 items) - Partially Fix - I will work for this in the end as this require careful changes.
- Access to static field locked on instance data - Fix
- Thread.sleep() - Not now
- call to native method 'currentThread()' in synchronized - It is for logging purpose, fix this
- Field accessed in both synchronized and unsynchronized contexts (22 items) - Fix **IMPORTANT**
- Non-private field accessed in synchronized context - Fix
- Synchronization on 'this' - FIX
- Synchronization on non-final - Fix
- Synchronized method (16 items) - Not fix now.
- wait without timeout - not fix
- while loop spings on field - not fix

##### Verbose or redundant code constructs (5 items) - Fix
- [x] #1013 Fix now

##### XML (18 items) - Fix
- [x] #1009 Minor issues, fix now

##### Other found by myself
- [x] #1010 BackgroundTask - Non of method/class use, so delete this class.
- [x] #1024 Remove unused HttpClient codes
