### ISSUE TITLE
Improve logging for local check point conflicted error

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1028]
##### Log message at  Listener side
https://gist.github.com/jamiltz/8bcfbaf9ffc54b9cf5c4

##### Error handling code at Replicator side
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L745-L748

Note: From replicator point of view, this could be happened,  not critical error, and recoverable.

##### TODO:
Listener side:
- [x] Remove `Exceptoin.printStackTrace()`: In general, this is not recommended for Couchbase Lite.
- [x] In case of Conflict, should not print stack trace. 
https://github.com/couchbase/couchbase-lite-java-core/blob/f43db5a4a853e5d041033fdb597d670641ee98c4/src/main/java/com/couchbase/lite/router/Router.java#L1897-L1898

Replicator Side:
- [x] Remove `Log.w(Log.TAG_SYNC, "%s: Unable to save remote checkpoint", e, this);`. Detailed log was printed in following codes.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L737

Extra:
- [x] Remove all `Exception.printStackTrace()`. Replace with `Log.e(...)`
