### ISSUE TITLE
Listener does not accept new connection

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1093]
Steps to reproduce is same with #1092

Notes: I believe all 20 threads in Thread-Pool of TJWS are in use. I suspect /_changes with longpoll REST API calls consume all threads on Listener

This issue might be root cause of issue #1092

**Comment by zgramana** [comment]
@hideki did we ever set the TJWS max connection count to be < the max thread pool size?

**Comment by hideki** [comment]
Not yet. Default maximum connection count is 100 or 200. And default thread pool size is 20. I am not sure what is best value for these on Android.

**Comment by hideki** [comment]
We apply following number as default value to avoid that the client waits till its request will be processed. In case all threads are used, the client can receive connection error immediately, so client can retry quickly.

`max thread pool == max connections + 1`
- max thread pool size => 21
- max connections => 20

**Comment by hideki** [comment]
It seems no maximum connection size setting. Based on TJWS code, it seems unlimited.

https://github.com/drogatkin/TJWS2/blob/3aca4a44155e57821a5eae0c36b163b1d072888f/1.x/src/Acme/Serve/Serve.java#L847-L860
```
while (running) {
	try {
	    Socket socket = acceptor.accept();
	    // TODO consider to use ServeConnection object pool
	    // TODO consider req/resp objects pooling
	    keepAliveCleaner.addConnection(new ServeConnection(socket, this));
	} catch (IOException e) {
    	log("TJWS: Accept: " + e);
	} catch (SecurityException se) {
    	log("TJWS: Illegal access: " + se);
	} catch (IllegalStateException is) {
    	log("TJWS: Illegal state: " + is);
	}
}
```

I misunderstood about `DEF_MAX_CONN_USE` parameter.
https://github.com/drogatkin/TJWS2/blob/3aca4a44155e57821a5eae0c36b163b1d072888f/1.x/src/Acme/Serve/Serve.java#L250-L253

**Comment by hideki** [comment]
### From previous thread-dump
https://gist.github.com/jamiltz/70fc1001f8fc1e34f103

##### Case 1: Thread-dump & its stacktrace: In case Thread is **WAITING** state by waiting for the response of Database.ChangesEvent for /_changes with longpoll
```
"Acme.Utils.ThreadPool(14)-PooledThread: Acme.Serve.Serve$ServeConnection@3f119084@22261" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(14)-PooledThread: Acme.Serve.Serve$ServeConnection@3f119084@22261
	  at java.lang.Object.wait(Object.java:-1)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:48)
	  - locked <0x571d> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:137)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x571e> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)
```
https://github.com/couchbase/couchbase-lite-java-listener/blob/master/src/main/java/com/couchbase/lite/listener/LiteServlet.java#L137

##### Case 2: Thread is **RUNNABLE** state, but thread is waitting for InputStream.read()
```
"Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@2d9a5b7f@22255" daemon prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.recvfromBytes(Posix.java:-1)
	  at libcore.io.Posix.recvfrom(Posix.java:185)
	  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	  at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
	  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
	  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
	  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	  at java.io.InputStream.read(InputStream.java:162)
	  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
	  - locked <0x5715> (a java.io.BufferedInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4290)
	  - locked <0x5716> (a Acme.Serve.Serve$ServeInputStream)
	  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4253)
	  at javax.servlet.ServletInputStream.readLine(ServletInputStream.java:93)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2041)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x5717> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)
```

### This time all threads of Thread-Pool are **Runnable** state. So I think they are **RUNNABLE**, but they are waiting for `InputStream.read()` like case 2 (above) in TJWS
```
*55	20874	Runnable	995	  67	Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@17435064	
*56	20875	Runnable	1666 227	Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@163454fa	
*61	21626	Runnable	364	  26	Acme.Utils.ThreadPool(2)-PooledThread: Acme.Serve.Serve$ServeConnection@4da49ce	
*62	21627	Runnable	2232 275	Acme.Utils.ThreadPool(3)-PooledThread: Acme.Serve.Serve$ServeConnection@1da2fcbb	
*63	21628	Runnable	1732 229	Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@f546169	
*64	21629	Runnable	368	  41	Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@1def7ee7	
*65	21630	Runnable	143	  27	Acme.Utils.ThreadPool(6)-PooledThread: Acme.Serve.Serve$ServeConnection@2234dec9	
*66	21636	Runnable	200	  14	Acme.Utils.ThreadPool(9)-PooledThread: Acme.Serve.Serve$ServeConnection@1e849e01	
*67	21632	Runnable	341	  36	Acme.Utils.ThreadPool(7)-PooledThread: Acme.Serve.Serve$ServeConnection@3d65371b	
*68	21633	Runnable	326	  48	Acme.Utils.ThreadPool(8)-PooledThread: Acme.Serve.Serve$ServeConnection@3389a82c	
*69	21640	Runnable	3348 320	Acme.Utils.ThreadPool(10)-PooledThread: Acme.Serve.Serve$ServeConnection@b3e7b6d	
*70	24077	Runnable	7	   0	Acme.Utils.ThreadPool(17)-PooledThread: Acme.Serve.Serve$ServeConnection@2078fda0	
*71	24034	Runnable	10	   4	Acme.Utils.ThreadPool(11)-PooledThread: Acme.Serve.Serve$ServeConnection@3b7fe2cd	
*72	24035	Runnable	33	  12	Acme.Utils.ThreadPool(12)-PooledThread: Acme.Serve.Serve$ServeConnection@1ef363df	
*73	24036	Runnable	35	   7	Acme.Utils.ThreadPool(13)-PooledThread: Acme.Serve.Serve$ServeConnection@3a8aed59	
*74	24037	Runnable	10	   3	Acme.Utils.ThreadPool(14)-PooledThread: Acme.Serve.Serve$ServeConnection@33740615	
*75	24038	Runnable	34	   4	Acme.Utils.ThreadPool(15)-PooledThread: Acme.Serve.Serve$ServeConnection@322647fc	
*76	24039	Runnable	197	  25	Acme.Utils.ThreadPool(16)-PooledThread: Acme.Serve.Serve$ServeConnection@208de7e8	
*77	24078	Runnable	2872 296	Acme.Utils.ThreadPool(18)-PooledThread: Acme.Serve.Serve$ServeConnection@3d8b76d9	
*78	24079	Runnable	18	   5	Acme.Utils.ThreadPool(19)-PooledThread: Acme.Serve.Serve$ServeConnection@21170ed0
```

Actually all threads in thread-pool are waiting at 
`len = in.readLine(lineBytes, 0, lineBytes.length);`
https://github.com/drogatkin/TJWS2/blob/master/1.x/src/Acme/Serve/Serve.java#L2173

**Comment by hideki** [comment]
### From master device's thread-dump
58 Threads (RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute) are blocked (waiting state). 
```
*49	31087	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@33de8066	
*53	30695	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3185c01d	
*57	24600	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@25d0948c	
*58	19991	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@527e8fc	
*59	31088	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2b6dd7fd	
*66	25793	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@c71b224	
*70	31306	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2d2381d6	
*75	25802	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3884863e	
*89	25867	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@28e8506e	
*93	25826	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1804884e	
*98	25880	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@358b94b8	
*105	25843	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@40d0eba	
107	0	unknown	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2bd4116b	
*112	31333	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@322de562	
*115	30539	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@31706472	
*117	30981	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3a4acfc3	
*121	30848	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@228a76c0	
*129	31111	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3549ba6d	
*133	31118	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@4602f0	
*139	31119	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@31dc7b8f	
*142	31120	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@277787fa	
*145	30636	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@276cef71	
*146	31121	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1da629c6	
*149	31122	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@bcb1c52	
*151	31126	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@7daab9e	
*152	31136	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@c1e3aa	
*154	31138	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3d4cf711	
*156	30762	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@29ce85de	
*157	31085	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1aa9b49a	
*158	30769	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3dbdd5d5	
*159	31139	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@272c52e4	
*160	31140	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@b2f3e02	
*161	30782	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2612fa51	
*163	31146	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1457384e	
*165	31166	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@af28b5a	
*166	30796	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@33bbea8d	
*168	31167	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@13be0326	
*172	31171	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@fba0703	
*173	31175	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@605f375	
*175	30811	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@ba7f566	
*178	30808	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@2860de45	
*179	30994	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1199688	
*180	30855	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3b3582ab	
*186	30858	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@277bd77f	
*189	30873	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1715d413	
*190	30878	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@157f9e6f	
*191	31016	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@e58aaf6	
*194	31023	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3d900b85	
*202	30945	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@e02aa47	
*203	30958	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@289db012	
*211	31051	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1df792a9	
*212	31052	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@347f55c	
*214	31063	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@147ef363	
*215	31062	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@8848d92	
*216	31064	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@24fd7819	
*217	31061	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@1c8b93f4	
*219	31072	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@39b0718d	
*220	31084	Wait	0	0	RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@5524d8e
```

### From previous master device's thread dump, it was 10 RefQueueWorker threads
https://gist.github.com/jamiltz/b40814dd0360b2778c82#file-thread-dump-master-L1440-L1548
Example
```
"RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3a31e093@23790" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@3a31e093@23790
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:422)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x5d59> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at org.apache.http.impl.conn.tsccm.RefQueueWorker.run(RefQueueWorker.java:102)
	  at java.lang.Thread.run(Thread.java:818)
```

### Note
- this might cause connection leak, and might cause thread-pool exhaustion.

### Potential solution
- Instead of create `HttpClinet` instance and `ConnectionManager` instance per request, Single HttpClient and ConnectionManager instance per `com.couchbase.lite.Manager` or per `Replicator`

**Comment by pasin** [comment]
I understand that those RefQueueWorkers are waiting for a new request to process (not in pending state). They are created by the connection manager. However it's really bad that a new connection manager gets created everytime when sending a http request. This is like we don't use connection pool but creating a new pool every time. Maybe if the connection magagers get GC, those worker might go away (not sure). 

Like @hideki said we should have only one shared connection manager per manager. I think we could have multiple http clients.

https://android.googlesource.com/platform/external/apache-http/+/froyo-release/src/org/apache/http/impl/conn/tsccm/RefQueueWorker.java

**Comment by pasin** [comment]
> HttpClient is fully thread-safe when used with a thread-safe connection manager such as MultiThreadedHttpConnectionManager. Please note that each respective thread of execution must have a local instance of HttpMethod and can have a local instance of HttpState or/and HostConfiguration to represent a specific host configuration and conversational state. At the same time the HttpClient instance and connection manager should be shared among all threads for maximum efficiency.

Look like one connection manager and one http client per replicator (per host configuration) would be best fit.

**Comment by pasin** [comment]
@hideki from the first doc, sound like httpclient also implements keep alive (persistent connection).

**Comment by hideki** [comment]
If we keep current code design about HttpClient, we might need to call [HttpClient.close()](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/AbstractHttpClient.html#close()), and also call [ClientConnectionManager.shutdown()](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ClientConnectionManager.html#shutdown()) just after HttpClient is used.

https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/AbstractHttpClient.html
> AbstractHttpClient is thread safe. It is recommended that the same instance of this class is reused for multiple request executions. When an instance of DefaultHttpClient is no longer needed and is about to go out of scope the connection manager associated with it must be shut down by calling ClientConnectionManager.shutdown()!

ToDo:
- make sure HttpClient and ClientConnectionManager is closed just after HttpClient is used.
- make sure to call `HttpEntity.consumeContent()` after finished to use `HttpEntity`
- make sure to close `InputStream` from `HttpEntity` after finished to use `InputStream`

**Comment by pasin** [comment]
I have tried with a simple scenario that one device (slave) has a listener up and another device has push and pull replicator running. On the device (master) that has push and pull replication, I also have a timer set to update one document every 10 seconds. I also keep creating some documents on both devices. Basically I tried to mimic F_B scenario.

When I brought the master device out of range (wait for 5 mins) and brought back, all documents were synced correctly but 2 connection threads out of 15 on the listener were blocked at the same place forever. See stacktrace here:


```
*25	26523	Runnable	135	45	Acme.Utils.ThreadPool(3)-PooledThread: Acme.Serve.Serve$ServeConnection@24523dd4	
  at libcore.io.Posix.recvfromBytes(Native Method)	
  at libcore.io.Posix.recvfrom(Posix.java:185)	
  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)	
  at libcore.io.IoBridge.recvfrom(IoBridge.java:553)	
  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)	
  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)	
  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)	
  at java.io.InputStream.read(InputStream.java:162)	
  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)	
  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)	
  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4285)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)	
  at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:460)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2307)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2288)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:286)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:458)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:547)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:454)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:577)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:440)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:591)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:440)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:527)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:454)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)	
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)	
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)	
  at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:200)	
  at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1181)	
  at java.lang.reflect.Method.invoke(Native Method)	
  at java.lang.reflect.Method.invoke(Method.java:372)	
  at com.couchbase.lite.router.Router.start(Router.java:504)	
  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:127)	
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)	
  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)	
  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)	
  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)	
  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)	
  at java.lang.Thread.run(Thread.java:818)	

*30	26528	Runnable	126	43	Acme.Utils.ThreadPool(7)-PooledThread: Acme.Serve.Serve$ServeConnection@25ef5d14	
  at libcore.io.Posix.recvfromBytes(Native Method)	
  at libcore.io.Posix.recvfrom(Posix.java:185)	
  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)	
  at libcore.io.IoBridge.recvfrom(IoBridge.java:553)	
  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)	
  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)	
  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)	
  at java.io.InputStream.read(InputStream.java:162)	
  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)	
  at java.io.BufferedInputStream.read(BufferedInputStream.java:295)	
  at Acme.Serve.Serve$ServeInputStream.read(Serve.java:4285)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipColon2(UTF8StreamJsonParser.java:2862)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipColon(UTF8StreamJsonParser.java:2808)	
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:704)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:570)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:440)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:547)	
  at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:454)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)	
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)	
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)	
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)	
  at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:200)	
  at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1181)	
  at java.lang.reflect.Method.invoke(Native Method)	
  at java.lang.reflect.Method.invoke(Method.java:372)	
  at com.couchbase.lite.router.Router.start(Router.java:504)	
  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:127)	
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)	
  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)	
  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)	
  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)	
  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)	
  at java.lang.Thread.run(Thread.java:818)	

```

**Comment by pasin** [comment]
@hideki Have you already worked on those todo items? If YES, I could try and see if it helps closing those half close stream.

**Comment by pasin** [comment]
I just quickly implemented calling `ClientConnectionManager.shutdown()` after finish using the HttpClient.  I couldn't reproduce the issue above (not 100% sure if that fixed issue or I just couldn't reproduce). 

However it clearly impacted the connection threads on the listener side. Now I can see only 5 connection threads active on the listener side instead of 10 - 14 while push and pull are running with actively pushing every 10 seconds.

**Comment by hideki** [comment]
## TODOs:

### First Step

#### calling HttpEntity.consumeContent()
- [ ] in BulkDownloader
- [ ] in ChangesTracker.java
- [ ] in RemoteMultipartDownloaderRequest
- [ ] in RemoteRequest

#### calling InputStream.close() from HttpEntity
- [ ] in BulkDownloader
- [ ] in ChangesTracker.java
- [ ] in RemoteMultipartDownloaderRequest
- [ ] in RemoteRequest

#### calling ClientConnectionManager.shutdown() after HttpClient was used.
- [ ] in BulkDownloader
- [ ] in PullerInternal
- [ ] in RemoteMultipartDownloaderRequest
- [ ] in RemoteMultipartRequest
- [ ] in RemoteRequest

### Second Step
- [ ] Make HttpClient instance and ClientConnectionManager per Replicator

Note why HttpClient instance per replicator 
- Authentication info should be set to HttpClient, it is per URL (replicator)
- CookieStore instance should be set to HttpClient, CookieStore should be unique per replicator

**Comment by hideki** [comment]
```
HttpClient.execute() - RequestWorker <-- not finished yet
  -> in callbBack
      -> submit task into WorkExecutor
         -> HttpClient.execute() <--- Blocked I guess from WorkExecutor  thread
```

```java
    public final HttpResponse execute(HttpHost target, HttpRequest request,
                                      HttpContext context)
        throws IOException, ClientProtocolException {


        
        // Initialize the request execution context making copies of 
        // all shared objects that are potentially threading unsafe.
        synchronized (this) {

            HttpContext defaultContext = createHttpContext();
            if (context == null) {
                execContext = defaultContext
```

**Comment by hideki** [comment]
Needs to call `HttpEntity.consumeContent()` even HTTP error. This makes connection leak.


http://stackoverflow.com/questions/4612573/exception-using-httprequest-execute-invalid-use-of-singleclientconnmanager-c
```java
    private InputStream getResource(String uri) {
        try {
            HttpGet method = new HttpGet(uri);
            HttpResponse httpResponse = client.execute(method);
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            InputStream is = null;
            if (HttpStatus.SC_OK == statusCode) {
                logger.debug("200 OK Amazon request");
                is = httpResponse.getEntity().getContent();
            } else {
                logger.debug("Something went wrong, statusCode is {}",
                        statusCode);
                 EntityUtils.consume(httpResponse.getEntity());
            }
            return is;
        } catch (Exception e) {
            logger.error("Something went terribly wrong", e);
            throw new RuntimeException(e);
        }
    }
```

**Comment by hideki** [comment]
Note: By this ticket, we will not fix that `HttpClient` instance is created whenever calling REST API. I will create other ticket for this.
