### ISSUE TITLE
1.3.1 Release close down tasks

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1401]
- [x] Run CBL Java/Android unit tests on devices (see: https://github.com/couchbase/couchbase-lite-java-core/issues/1401#issuecomment-242826924)
- [x] Run performance sanity tests Nexus 6 (Android M) - [Result] (https://github.com/couchbase/couchbase-lite-java-core/wiki/Performance-Test-Result) - push/pull replication speed is slower than 1.3.0. #1416
- [x] Build native libraries for OSX and Windows (SQLite/ForestDB), and append it in jar file
- [x] Verify built binaries on Couchbase maven
- [x] Verify Zipped built binaries, which are used for download
- [x] Create and verify phongap plugin
- [x] Create package and publish to JCenter
- [x] Create package and publish to Maven Central
- [x] Tag release on github repo

**Comment by hideki** [comment]
## Unit Test Tasks
#### CBL Java Unit Test
- [ ] Windows -> two tests fail https://github.com/couchbase/couchbase-lite-android/issues/980
- [x] OSX
- [x] Linux

#### CBL Android Unit Test on devices
- [x] Nexus 4 (Android 4.2 API 17)
- [x] Nexus 5 (Android 6.0 API 23)
- [x] Nexus 6 (Android 6.0 API 23)
- [x] Nexus 9 (Android 7.0 API 24)

**Comment by hideki** [comment]
#### PhoneGap Test

- [ ] 1.3.1-10

Issues:
- https://github.com/couchbaselabs/TodoLite-PhoneGap/issues/24
