### ISSUE TITLE
Catch up latest (v1.1) SQLite table schema and SQL queries 

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#628]
- [x] Remove maps table, updates all associated codes.
- [x] Remove attachments table, updates all associated codes.
- [x] Catch up latest (v1.1) Database File layout #629  (CBLDatabaseUpgrade.m)
- [x] Implement migration logic from v1.0 to v1.1 table schema #660
- [x] Code refactoring

**Comment by hideki** [comment]
- Remove attachments table
- Remove maps table
