### ISSUE TITLE
Implement pluggable storage engine

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#644]
See iOS implementation, e.g. [CBL_Storage.h](https://github.com/couchbase/couchbase-lite-ios/blob/d2a91262e93377f5dea57777b92a7c152665577f/Source/CBL_Storage.h), [CBL_ViewStorage.h](https://github.com/couchbase/couchbase-lite-ios/blob/0990b1d6327f715d770e138187f8308818079393/Source/CBL_ViewStorage.h) , etc.

**Comment by hideki** [comment]
Action Items
- [ ] Separate Interface and Implementation for Database, View, and Query
- [ ] Declare Interface for Database, View, and Query
- [ ] Refactor Implementation for Database, View, and Query 
- [ ] Catch up latest (v1.1) SQLite table schema and SQL queries
- [ ] Implement migration logic from v1.0 to v1.1 table schema
