### ISSUE TITLE
Complete CBForest-Java Implmentation and Test

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#697]

**Comment by hideki** [comment]
Remaining Tasks
- [ ] Figure out forestdb crash issue on Nexus 6 (Real device)
- [ ] Make compilable with cbforest (02c893c) and forestdb (0d4e7dd) - These are commits of CBL iOS 1.1.0
- [ ] Run cbforest-java test with above submodules and fixed issues if found
- [ ] Wrote tests that are covered by cbforest iOS test cases
- [ ] As current test is not unit test, it is regular app. Convert current tests to unit tests

**Comment by hideki** [comment]
Note to Self:
- Current implementation is just wrapper of cbforest. Performance could not be good enough because current implementation expects many JNI calls.
- To improve performance, needs to write more rich classes or methods in native side (C++), or needs to move some of functionalities to java side.
