### ISSUE TITLE
Add support for SQLCipher

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#702]

**Comment by mjaszczyk** [comment]
Hi guys,
is there any estimation on this feature? When are you planning to release it? I will be very thankful for an answer.

**Comment by pasin** [comment]
This was scheduled to v1.2.0. I don't have information about the time to release.

**Comment by pasin** [comment]
Task Breakdown:
- [ ] Research on SQLCipher libraries for Java/Android
  - [ ] https://github.com/sqlcipher/sqlcipher
  - [ ] https://github.com/sqlcipher/android-database-sqlcipher
- [ ] SQLCipher Native Build (Gradle/Make and Android NDK)
- [ ] Java and Android SQLiteStorageEngine
  - [ ] Develop a unified engine (Key: CBL Android Shared DB and Threading Model and Nested Transactions)
  - [ ] Integrate with both CBL Android and Java
- [ ] Test and Performance Measurement

**Comment by pasin** [comment]
Updated task breakdown:
Phrase 1:
- [x] Test [android-database-sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher). 
- [x] Create Android library (Gradle) project for android-database-sqlcipher
- [x] Implement database encryption API. Users select to use android-database-sqlcipher for encryption.
- [x] Test and bug fixes

Phrase 2:
- [ ] Fix android-database-sqlcipher built for 64 bit binary

Phrase 3:
- [ ] Integrate SQLCipher (native) to couchbase-lite-java (update build.gradle)
- [ ] Enhance couchbase-lite-java SQLite storage engine (Long term goal : be able to use this for couchbase-lite-android as well)
