### ISSUE TITLE
ForestDB storage Performance improvement

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#704]
- [x] Measure ForestDB storage performance and compare with SQLite storage
- [ ] Improve slow methods/features

**Comment by hideki** [comment]
Test results with initial implementation
https://github.com/couchbase/couchbase-lite-java-core/issues/715#issuecomment-139112963

**Comment by hideki** [comment]
Tasks for improvement:
- [ ] Reduce number of JNI calls per operation
- [ ] Investigate why iteration is slow
- [ ] Review calling java map function from native

**Comment by hideki** [comment]
Result with CBForest C API binding: https://github.com/couchbase/couchbase-lite-java-core/issues/715#issuecomment-152645872
