### ISSUE TITLE
Some UnitTest fails with forestdb storage on Java Desktop (Mac OSX)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#721]
ApiTest failures are already taken care by other tickets.

ChangesTest
- [x] testChangeNotification (Java and Android) -> #740

ViewTest
- [x] testViewQuery (SQLIte)  (Java and Android) -> #738
- [x] testDeleteView (SQLIte)  (Java and Android) -> #738

ReplicationTest
- testAllLeafRevisionsArePushed (Java and Android) -> #712  
- testContinuousPushReplicationGoesIdleTooSoon  (Java and Android) -> #717 

BatcherTest
- [x] testBatcherWaitsForProcessorDelay2 (Java and Android) -> #713

Not many test failures are remaining.

**Comment by hideki** [comment]
Additional Test failures

ReplicationTest
- [ ]  testMockPullBulkDocsSyncGw - infinite loop on nexus 6 (test executed from IDE)
- [ ] testPusherBatching - Native Crash on nexus 6
- [ ] testAttachmentsDeletedOnPull - emulator - Nexus_4_API_19_arm(AVD) - 4.4.4
- [ ]  testCallReplicateTwice - on nexus 6

**Comment by hideki** [comment]
Infomation about testMockPullBulkDocsSyncGw() failure


```
junit.framework.AssertionFailedError
at com.couchbase.lite.LiteTestCase.runReplication(LiteTestCase.java:594)
at com.couchbase.lite.replicator.ReplicationTest.mockPullBulkDocs(ReplicationTest.java:3271)
at com.couchbase.lite.replicator.ReplicationTest.testMockPullBulkDocsSyncGw(ReplicationTest.java:3220)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:844)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by hideki** [comment]
Crash log of ReplicationTest. testPusherBatching()

Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details

https://gist.github.com/hideki/35b4355c02373c3891da

**Comment by hideki** [comment]
Another crash log
https://gist.github.com/hideki/57779a687b7f933527e7


Crash might be cased by following
```
E/CBForest( 3391): FORESTDB ERROR -39
```

**Comment by hideki** [comment]
It seems ForestDBStore or CBForest tried to abort Transaction middle or transaction.

```c++
    /**
     * DB handle is being used by another thread. Forestdb handles must not be
     * shared among multiple threads.
     */
    FDB_RESULT_HANDLE_BUSY = -39,
```

```c++
fdb_status _fdb_abort_transaction(fdb_kvs_handle *handle)
{
    file_status_t fstatus;
    struct filemgr *file;

    if (handle->txn == NULL) {
        // there is no transaction started
        return FDB_RESULT_TRANSACTION_FAIL;
    }
    if (handle->kvs) {
        if (handle->kvs->type == KVS_SUB) {
            // deny transaction on sub handle
            return FDB_RESULT_INVALID_HANDLE;
        }
    }

    if (!atomic_cas_uint8_t(&handle->handle_busy, 0, 1)) {
        return FDB_RESULT_HANDLE_BUSY;
    }
```

**Comment by hideki** [comment]
New Log with stack trace
https://gist.github.com/hideki/165bc7b45298fd551058

```
09-17 21:46:10.647    1053-1322/? E/CBForest﹕ FORESTDB ERROR -39
09-17 21:46:10.647    1053-1322/? I/app_name﹕ # 0: 0xa7eaf7c4  _ZN8forestdb16captureBacktraceEPPvj
    # 1: 0xa7eafac4  _ZN8forestdb17backtraceToLogcatEv
    # 2: 0xa7eafc74
    # 3: 0xa7eafd60  _ZN8forestdb4_LogENS_8logLevelEPKcz
    # 4: 0xa7ec0efc
    # 5: 0xa7ec13fc
    # 6: 0xa7ec1294  _ZNK8forestdb8KeyStore4readERNS_8DocumentENS0_14contentOptionsE
    # 7: 0xa7ecc5dc  _ZN8forestdb17VersionedDocument4readEv
    # 8: 0xa7ecc520  _ZN8forestdb17VersionedDocumentC2ENS_8KeyStoreENS_5sliceE
    # 9: 0xa7ee8168  _ZN3CBF17VersionedDocumentC2ERNS_8KeyStoreERNS_5SliceE
    #10: 0xa7efd980  Java_com_couchbase_lite_cbforest_cbforestJNI_new_1VersionedDocument_1_1SWIG_10
    #11: 0xb5a56bd0  dvmPlatformInvoke
    #12: 0xb5a86f02  _Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread
    #13: 0xb5a71740  _Z21dvmCheckCallJNIMethodPKjP6JValuePK6MethodP6Thread
    #14: 0xb5a5ffe4
    #15: 0xb5a66f38  _Z11dvmMterpStdP6Thread
    #16: 0xb5a645d0  _Z12dvmInterpretP6ThreadPK6MethodP6JValue
    #17: 0xb5a99318  _Z14dvmCallMethodVP6ThreadPK6MethodP6ObjectbP6JValueSt9__va_list
    #18: 0xb5a9933c  _Z13d
```

**Comment by hideki** [comment]
ReplicationTest.testPusherBatching()
another crash log
https://gist.github.com/hideki/3cfa140bd939987ee653

**Comment by hideki** [comment]
Some new test failures

```
com.couchbase.lite.replicator.ReplicationTest > testContinuousPushReplicationGoesIdleTooSoon[Nexus_4_API_19_arm(AVD) - 4.4.4] FAILED 
	junit.framework.AssertionFailedError: expected:<25> but was:<23>
	at com.couchbase.lite.replicator.ReplicationTest.testContinuousPushReplicationGoesIdleTooSoon(ReplicationTest.java:3652)


com.couchbase.lite.replicator.ReplicationTest > testPusherBatching[Nexus_4_API_19_arm(AVD) - 4.4.4] FAILED 
	junit.framework.AssertionFailedError: expected:<15> but was:<13>
	at com.couchbase.lite.replicator.ReplicationTest.testPusherBatching(ReplicationTest.java:1999)
```

**Comment by hideki** [comment]
testPusherBatching - failed during getRevisionHistory
```java
09-21 15:38:24.856 2291-2310/com.couchbase.lite.test W/Database: [changesSince()] revID => 1-a951becdcd0abe51a96444189c0f4fa2
09-21 15:38:24.856 2291-2310/com.couchbase.lite.test W/Database: [changesSince()] revID => 1-a60dee3aada93de5ca734373f2b571ef
09-21 15:38:25.336 2291-2312/com.couchbase.lite.test E/CBForest: FORESTDB ERROR -39
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database: %%%%% Error in getRevisionHistory() rev={49641dd7-b551-4bca-bb04-c0cf38692968 #1-8464c420c20b62b82e80d522859a1cf8}
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database: java.lang.Exception: -39
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.cbforest.cbforestJNI.new_VersionedDocument__SWIG_0(Native Method)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.cbforest.VersionedDocument.<init>(VersionedDocument.java:39)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.store.ForestDBStore.getRevisionHistory(ForestDBStore.java:422)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.Database.getRevisionHistory(Database.java:1762)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1216)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:482)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:300)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:250)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-21 15:38:25.426 2291-2312/com.couchbase.lite.test E/Database:     at java.lang.Thread.run(Thread.java:841)
09-21 15:38:25.726 2291-2313/com.couchbase.lite.test E/RemoteRequest: Got error status: 404 for http://10.0.2.2:4984/db/_local/8ead10fa5c02ade2c8264963e7eeeff005528ecf.  Reason: NOT FOUND
09-21 15:38:25.736 2291-2313/com.couchbase.lite.test W/Sync: com.couchbase.lite.replicator.ReplicationInternal$7@b1d887e0: Unable to save remote checkpoint
```
