### ISSUE TITLE
Enhance forestdb storage performance

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#733]
Test results with initial implementation
https://github.com/couchbase/couchbase-lite-java-core/issues/715#issuecomment-139112963

Tasks:
- [ ] Reduce number of JNI calls per operation
- [ ] Investigate why iteration is slow
- [ ] Review calling java map function from native

**Comment by hideki** [comment]
Duplicated with #704
